apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREV4TURneApNakUxTURsYUZ3MDBNREV4TURneE1qRTFNRGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDay9Sd1V1UldES085TmtPdGZvcFlYT0RUNlJIbFJJenU2RWI2eDZNZStWay9lVFgxRApmczY1cWlUNkZOclF0Z3BId3EyT3ZrK2VSWkZoL2M3bEZjc0tCVFBSL1NwZTNRSlc4T3RkdisyVm9IaGlnNEZuCnU0bXBydHo3OUEwdUVQb3lLSVBINUUxc3J1OWZOc05uTUNpbFBVc0FFa0szd2VpSlZWS2EyL2FYVFJoSjR2RHAKWEl3QW5JVmVJTFVUWFcvenk3SU5DLzQ5Q09qTjlaeFRqaDV2MU5ib0Y0cGtrSko5V3V1dmpkSEUxTFMrWTdGWApmSDZOUjJQaERmdjhsWGxvNXNJSzkyaWEzRmdVMDUyYW1NOExrQUk1UFFpNzBtVm5Fa1NnUzUyRDlnNHcxck9LCitDVWFIU29JOVdPYWF4TjlCUDRZTDI4TVNOTVhGWEI0S2hzQkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJxSWdIYVVUZXBCenBIOTlYNQpqNjdDdG45Sk5qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmU09BQ0tZZlBHbSswVnltNlVETWhvZHhEbEdDCnFLN1BCZmtCelREUXdnODcxUWJCcEFWSFVVUUJ6WEJVa2NmeHVaQlkzS1gzLzhqcmRzSUhaTllyYVVhMHpvOW0KY1FUalVQK1UrTWN1YzZ0M1hRbnlSVDNYVVorREdLVHowWlQ5SDVWQzkzNjl4U29SQVEyemgwb2VUS0NFYXBxNApCRDczdm5kQ3pUV3llaE5UbWZwWnlySDl4cmZVZHFVV2lNeWRmSlp3SGphdTZxL1pVZk1ZU045ZEl2NlllMWNnCkh2NWJDY1BOWU9ic000cW9ncEMrTVYwbGhKQTMxMlVUanJmaCs3NnJUNHNPZ0pRbGg4bEZtMVVFSWhqNGhoSDAKZitBWTFzeE54ejVINENmbFNjZHZobW4zRDdkdCs2WlJGaXZQalhGMjBQais5RlA2dHFTemd4TGRkQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0e48f3d6-5095-40f5-b441-f200019dc9f3.k8s.ondigitalocean.com
  name: do-sfo2-k8s-1-19-3-do-2-sfo2-1604837694223
contexts:
- context:
    cluster: do-sfo2-k8s-1-19-3-do-2-sfo2-1604837694223
    user: do-sfo2-k8s-1-19-3-do-2-sfo2-1604837694223-admin
  name: do-sfo2-k8s-1-19-3-do-2-sfo2-1604837694223
current-context: do-sfo2-k8s-1-19-3-do-2-sfo2-1604837694223
kind: Config
preferences: {}
users:
- name: do-sfo2-k8s-1-19-3-do-2-sfo2-1604837694223-admin
  user:
    token: 667172d3366f3d024b4bc8ff98c1f280bb43cdef63223f74c074b91f15d64008
