name: Build
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Deploy Image
        working-directory: ./auth
        run: |
          docker build -f Dockerfile -t 11071994/auth .
          docker push 11071994/auth

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG | base64 }}

      - uses: actions-hub/kubectl@master
        with:
          args: get nodes

  



