name: Build
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - uses: actions/checkout@v2
        name: Build and Deploy Image
        run: |
        docker build -f Dockerfile -t 11071994/auth auth/Dockerfile


