name: Build
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Deploy Image
        working-directory: ./auth
        run: |
          docker build -f Dockerfile -t 11071994/auth .
          docker push 11071994/auth

      - name: Install kubernetes
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Attach digital ocean clustera
        run: mv k8s-1-19-3-do-2-sfo2-1604833180975-kubeconfig.yaml .kube/config

      - name: Get nodes
        run: kubectl get nodes -o wide



